version: 2

sources:
    - name: staging
      # database: taxi-rides-ny-339813
      database: smart-grin-376216
      schema: trips_data_all

      tables:
        - name: green_tripdata
        - name: yellow_tripdata